<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.codgen</groupId>
        <artifactId>codgen</artifactId>
        <version>1.2.25</version>
    </parent>
    <artifactId>codgen-java</artifactId>
    <name>codgen-java</name>
    <description>解析Java源文件并根据模板生成新文件</description>

    <properties>
        <mainClass>io.github.codgen.java.CodgenJavaApplication</mainClass>

        <native-image-maven-plugin.version>21.2.0</native-image-maven-plugin.version>
        <native-maven-plugin.version>0.10.1</native-maven-plugin.version>
        <maven-surefire-plugin.version>3.1.2</maven-surefire-plugin.version>
        <build-helper-maven-plugin.version>3.5.0</build-helper-maven-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.codgen</groupId>
                <artifactId>codgen</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.github.rebue.wheel</groupId>
            <artifactId>wheel-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.yomahub</groupId>
            <artifactId>liteflow-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.yomahub</groupId>
            <artifactId>liteflow-script-javax-pro</artifactId>
        </dependency>
        <dependency>
            <groupId>com.yomahub</groupId>
            <artifactId>liteflow-script-graaljs</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.javaparser</groupId>
            <artifactId>javaparser-symbol-solver-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.ibeetl</groupId>
            <artifactId>beetl</artifactId>
        </dependency>

        <!-- logback配置使用if需要 -->
        <dependency>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>janino</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <!-- 生成native-image的配置文件需要 -->
            <!-- 因为是利用test插件生成，所以不能skip test -->
            <!-- maven命令使用test，并最好加上 '-Dtest=CodgenApplicationTests#testMain' 参数限定测试的方法 -->
            <id>gen-native-image-config</id>
            <build>
                <plugins>
                    <!-- 执行测试用例的插件 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven-surefire-plugin.version}</version>
                        <configuration>
                            <argLine>
                                -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image
                            </argLine>
                            <includes>
                                <include>**/CodgenJavaApplicationTests.java</include>
                            </includes>
                            <skip>false</skip>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>${native-maven-plugin.version}</version>
                        <!-- enable JUnit Platform test listener mode -->
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                            <execution>
                                <id>test-native</id>
                                <goals>
                                    <goal>test</goal>
                                </goals>
                                <phase>test</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <buildArgs>
                                <!-- 建立独立镜像，不成功则报告失败 -->
                                --no-fallback
                                <!-- 指定native-image配置文件的目录(此目录由maven编译gen-native-image-config生成) -->
                                -H:ConfigurationFileDirectories=src/main/resources/META-INF/native-image/
                                <!-- 级别设置为3，打包时输出包含的资源文件 -->
                                -H:Log=registerResource:3
                            </buildArgs>
                            <mainClass>${mainClass}</mainClass>
                            <!-- native-image编译时输出详细的日志 -->
                            <verbose>true</verbose>
                            <!-- 生成调试信息 -->
                            <debug>true</debug>
                            <!-- 快速编译 -->
                            <quickBuild>true</quickBuild>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
